
/*
libname teralib teradata server=server user=userid pwd=pass schema=db;
*/

libname censo '~/my_shared_file_links/u60151886/Censo_2010';


PROC SQL;

	/*CREATE TABLE SQL_EJEMPLO1 AS*/
	SELECT ENT, COUNT(*) AS NUM_REGISTROS, COUNT(DISTINCT MUN) AS NUM_MUNICIPIOS
		FROM CENSO.VIVIENDAS_01_A
			WHERE ENT = '01'
				GROUP BY ENT
				ORDER BY ENT;				
QUIT;



PROC SQL;

	SELECT ENT, COUNT(*) AS NUM_REGISTROS, COUNT(DISTINCT MUN) AS NUM_MUNICIPIOS, COUNT(DISTINCT AGEB) AS NUM_AGEB
		FROM CENSO.VIVIENDAS_29_B
			WHERE ENT = '29'
				GROUP BY ENT
				ORDER BY ENT;				
QUIT;




* LA VENTAJA ES QUE SE PUEDEN UTILIZAR OPCIONES DE LOS PASO DATA;

PROC SQL;

	SELECT ENT, MUN, 
	COUNT(*) AS NUM_REGISTROS, COUNT(DISTINCT AGEB) AS NUM_AGEB, COUNT(DISTINCT LOC) AS NUM_LOCS 
		FROM CENSO.VIVIENDAS_29_B /*(KEEP = ENT MUN AGEB LOC)*/
			WHERE MUN IN ('001','005','013','035')
				GROUP BY ENT, MUN
				ORDER BY ENT, MUN;				
QUIT;







